### ISSUE TITLE
BREAKING: startup error after forced upgrade to 0.1.4-pre1

### ISSUE THREAD

**Issue by fungilation** [raix/Meteor-handlebar-helpers#40]
Meteor update today forced upgrade from 0.1.3 without a way to downgrade:
```
$ meteor add raix:handlebar-helpers@0.1.3
                                              
In order to resolve constraints, we had to use the following
experimental package versions:
  raix:handlebar-helpers@0.1.4-pre1  Handlebar helpers

  added raix:handlebar-helpers at version 0.1.4-pre1
                                              
raix:handlebar-helpers: Handlebar helpers
```

Crashing console error on meteor startup:
```
W20141201-16:19:23.491(-8)? (STDERR) ~/.meteor/packages/meteor-tool/.1.0.35.158k7ak++os.osx.x86_64+web.browser+web.cordova/meteor-tool-os.osx.x86_64/dev_bundle/lib/node_modules/fibers/future.js:173
W20141201-16:19:23.491(-8)? (STDERR) 						throw(ex);
W20141201-16:19:23.491(-8)? (STDERR) 						      ^
W20141201-16:19:23.492(-8)? (STDERR) ReferenceError: Deps is not defined
W20141201-16:19:23.492(-8)? (STDERR)     at Package (packages/raix:handlebar-helpers/common.js:14)
W20141201-16:19:23.493(-8)? (STDERR)     at APP/.meteor/local/build/programs/server/packages/raix_handlebar-helpers.js:73:4
W20141201-16:19:23.493(-8)? (STDERR)     at APP/.meteor/local/build/programs/server/packages/raix_handlebar-helpers.js:82:3
W20141201-16:19:23.493(-8)? (STDERR)     at APP/.meteor/local/build/programs/server/boot.js:168:10
W20141201-16:19:23.493(-8)? (STDERR)     at Array.forEach (native)
W20141201-16:19:23.494(-8)? (STDERR)     at Function._.each._.forEach (~/.meteor/packages/meteor-tool/.1.0.35.158k7ak++os.osx.x86_64+web.browser+web.cordova/meteor-tool-os.osx.x86_64/dev_bundle/lib/node_modules/underscore/underscore.js:79:11)
W20141201-16:19:23.494(-8)? (STDERR)     at APP/.meteor/local/build/programs/server/boot.js:82:5
=> Exited with code: 8
=> Your application is crashing. Waiting for file change.
```

**Comment by serkandurusoy** [comment]
Marking closed due to long-time inactivity. Please reopen if you still experience the same problem. Thanks for reporting.
